# Generated by Django 5.2.7 on 2025-10-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('report_year', models.CharField(blank=True, max_length=20, null=True)),
                ('report_month', models.CharField(blank=True, max_length=20, null=True)),
                ('person_days', models.CharField(blank=True, max_length=50, null=True)),
                ('expenditure', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mgnrega_district_performance',
            },
        ),
    ]
